Update ESXi Provider to josenk
Update ESXi provider to josenk from hashicorp/esxi

```
DetectionLab/ESXi terraform init && terraform apply                                                                                                                             

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/esxi...

Error: Failed to install provider

Error while installing hashicorp/esxi: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/esxi
```